services:
  - type: web
    name: grocery-backend-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: grocery-db
          property: connectionString
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 10080
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: grocery-db
    databaseName: grocery
    user: grocery_user